// Mocks generated by Mockito 5.4.4 from annotations
// in real_time_expense_tracker/test/unit/usecases/add_expense_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:real_time_expense_tracker/core/errors/failures.dart' as _i5;
import 'package:real_time_expense_tracker/domain/entities/expense.dart' as _i6;
import 'package:real_time_expense_tracker/domain/repositories/expense_repository.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ExpenseRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockExpenseRepository extends _i1.Mock implements _i3.ExpenseRepository {
  MockExpenseRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.Expense>> createExpense(
          _i6.Expense? expense) =>
      (super.noSuchMethod(
        Invocation.method(
          #createExpense,
          [expense],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, _i6.Expense>>.value(
            _FakeEither_0<_i5.Failure, _i6.Expense>(
          this,
          Invocation.method(
            #createExpense,
            [expense],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i6.Expense>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.Expense>> getExpenseById(String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getExpenseById,
          [id],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, _i6.Expense>>.value(
            _FakeEither_0<_i5.Failure, _i6.Expense>(
          this,
          Invocation.method(
            #getExpenseById,
            [id],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i6.Expense>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.Expense>> updateExpense(
          _i6.Expense? expense) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateExpense,
          [expense],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, _i6.Expense>>.value(
            _FakeEither_0<_i5.Failure, _i6.Expense>(
          this,
          Invocation.method(
            #updateExpense,
            [expense],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i6.Expense>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> deleteExpense(String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteExpense,
          [id],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
            _FakeEither_0<_i5.Failure, void>(
          this,
          Invocation.method(
            #deleteExpense,
            [id],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> deleteMultipleExpenses(
          List<String>? ids) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteMultipleExpenses,
          [ids],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
            _FakeEither_0<_i5.Failure, void>(
          this,
          Invocation.method(
            #deleteMultipleExpenses,
            [ids],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, bool>> expenseExists(String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #expenseExists,
          [id],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, bool>>.value(
            _FakeEither_0<_i5.Failure, bool>(
          this,
          Invocation.method(
            #expenseExists,
            [id],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, bool>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.Expense>>> getExpenses({
    DateTime? startDate,
    DateTime? endDate,
    String? categoryId,
    _i6.ExpenseType? type,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getExpenses,
          [],
          {
            #startDate: startDate,
            #endDate: endDate,
            #categoryId: categoryId,
            #type: type,
          },
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, List<_i6.Expense>>>.value(
                _FakeEither_0<_i5.Failure, List<_i6.Expense>>(
          this,
          Invocation.method(
            #getExpenses,
            [],
            {
              #startDate: startDate,
              #endDate: endDate,
              #categoryId: categoryId,
              #type: type,
            },
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, List<_i6.Expense>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.Expense>>> getExpensesByDate(
          DateTime? date) =>
      (super.noSuchMethod(
        Invocation.method(
          #getExpensesByDate,
          [date],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, List<_i6.Expense>>>.value(
                _FakeEither_0<_i5.Failure, List<_i6.Expense>>(
          this,
          Invocation.method(
            #getExpensesByDate,
            [date],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, List<_i6.Expense>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.Expense>>>
      getExpensesByDateRange({
    required DateTime? startDate,
    required DateTime? endDate,
  }) =>
          (super.noSuchMethod(
            Invocation.method(
              #getExpensesByDateRange,
              [],
              {
                #startDate: startDate,
                #endDate: endDate,
              },
            ),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, List<_i6.Expense>>>.value(
                    _FakeEither_0<_i5.Failure, List<_i6.Expense>>(
              this,
              Invocation.method(
                #getExpensesByDateRange,
                [],
                {
                  #startDate: startDate,
                  #endDate: endDate,
                },
              ),
            )),
          ) as _i4.Future<_i2.Either<_i5.Failure, List<_i6.Expense>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.Expense>>> getExpensesByCategory(
    String? categoryId, {
    DateTime? startDate,
    DateTime? endDate,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getExpensesByCategory,
          [categoryId],
          {
            #startDate: startDate,
            #endDate: endDate,
          },
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, List<_i6.Expense>>>.value(
                _FakeEither_0<_i5.Failure, List<_i6.Expense>>(
          this,
          Invocation.method(
            #getExpensesByCategory,
            [categoryId],
            {
              #startDate: startDate,
              #endDate: endDate,
            },
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, List<_i6.Expense>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.Expense>>> getRecentExpenses(
          {int? limit = 10}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRecentExpenses,
          [],
          {#limit: limit},
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, List<_i6.Expense>>>.value(
                _FakeEither_0<_i5.Failure, List<_i6.Expense>>(
          this,
          Invocation.method(
            #getRecentExpenses,
            [],
            {#limit: limit},
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, List<_i6.Expense>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.Expense>>> searchExpenses(
          String? query) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchExpenses,
          [query],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, List<_i6.Expense>>>.value(
                _FakeEither_0<_i5.Failure, List<_i6.Expense>>(
          this,
          Invocation.method(
            #searchExpenses,
            [query],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, List<_i6.Expense>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, double>> getTotalAmount({
    DateTime? startDate,
    DateTime? endDate,
    _i6.ExpenseType? type,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTotalAmount,
          [],
          {
            #startDate: startDate,
            #endDate: endDate,
            #type: type,
          },
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, double>>.value(
            _FakeEither_0<_i5.Failure, double>(
          this,
          Invocation.method(
            #getTotalAmount,
            [],
            {
              #startDate: startDate,
              #endDate: endDate,
              #type: type,
            },
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, double>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, double>> getTotalExpensesByCategory(
          String? categoryId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTotalExpensesByCategory,
          [categoryId],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, double>>.value(
            _FakeEither_0<_i5.Failure, double>(
          this,
          Invocation.method(
            #getTotalExpensesByCategory,
            [categoryId],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, double>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, Map<String, double>>> getExpenseStats({
    DateTime? startDate,
    DateTime? endDate,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getExpenseStats,
          [],
          {
            #startDate: startDate,
            #endDate: endDate,
          },
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, Map<String, double>>>.value(
                _FakeEither_0<_i5.Failure, Map<String, double>>(
          this,
          Invocation.method(
            #getExpenseStats,
            [],
            {
              #startDate: startDate,
              #endDate: endDate,
            },
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, Map<String, double>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> syncExpenses() =>
      (super.noSuchMethod(
        Invocation.method(
          #syncExpenses,
          [],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
            _FakeEither_0<_i5.Failure, void>(
          this,
          Invocation.method(
            #syncExpenses,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, double>> getTotalExpenses() =>
      (super.noSuchMethod(
        Invocation.method(
          #getTotalExpenses,
          [],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, double>>.value(
            _FakeEither_0<_i5.Failure, double>(
          this,
          Invocation.method(
            #getTotalExpenses,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, double>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.Expense>> addExpense(
          _i6.Expense? expense) =>
      (super.noSuchMethod(
        Invocation.method(
          #addExpense,
          [expense],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, _i6.Expense>>.value(
            _FakeEither_0<_i5.Failure, _i6.Expense>(
          this,
          Invocation.method(
            #addExpense,
            [expense],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i6.Expense>>);
}
